### root ping
GET http://localhost

### get list
GET http://localhost:5000/products

### get product by id
GET http://localhost:5000/products/a6f70305-88af-4c5e-bad1-ab5ea7fc974b

### update product stock
PUT http://localhost:5000/products/a6f70305-88af-4c5e-bad1-ab5ea7fc974b/stock
content-type: application/json

{
    "stock": 100
}

### update product price
PUT http://localhost:5000/products/a6f70305-88af-4c5e-bad1-ab5ea7fc974b/price
content-type: application/json

{
    "price": 12
}

### create product
POST http://localhost:5000/products
content-type: application/json

{
    "name": "product3",
    "price": 14,
    "stock": 21
}


### delete product
DELETE http://localhost:5000/products/a6f70305-88af-4c5e-bad1-ab5ea7fc974b