GET http://localhost:5000

###

GET http://localhost:5000/products

###

GET http://localhost:5000/products/d38971d6-0468-4bc7-9f07-01ead4fb96ef

###
PUT http://localhost:5000/products/d38971d6-0468-4bc7-9f07-01ead4fb96ef/stock
content-type: application/json

{
    "stock": 20
}


